PUT http://localhost:8080/events/2
content-type: application/json

{
    "name": "Updated event",
    "description": "An updated event",
    "location": "An updated location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}